//autogenerated:yes
//nolint:revive,lll
package mower_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type DockingSensor struct {
    msg.Package `ros:"mower_msgs"`
    Stamp time.Time
    DetectedLeft uint8
    DetectedRight uint8
}

