//autogenerated:yes
//nolint:revive,lll
package mower_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type Emergency struct {
    msg.Package `ros:"mower_msgs"`
    Stamp time.Time
    ActiveEmergency bool
    LatchedEmergency bool
    Reason string
}

