//autogenerated:yes
//nolint:revive,lll
package mower_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type PerimeterControlSrvReq struct {
    msg.Package `ros:"mower_msgs"`
    ListenOn uint8`rosname:"listenOn"`
}



type PerimeterControlSrvRes struct {
    msg.Package `ros:"mower_msgs"`
}

type PerimeterControlSrv struct {
    msg.Package `ros:"mower_msgs"`
    PerimeterControlSrvReq
    PerimeterControlSrvRes
}
