//autogenerated:yes
//nolint:revive,lll
package mower_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "time"
)


type Power struct {
    msg.Package `ros:"mower_msgs"`
    Stamp time.Time
    ChargeVoltageAdc float32
    ChargeVoltageChg float32
    ChargeCurrent float32
    BatteryVoltageAdc float32
    BatteryVoltage float32
    PercentBattery float32
    DCDCInputCurrent float32
    ChargerInputCurrent float32
    ChargerEnabled bool
    ChargerStatus string
}

