//autogenerated:yes
//nolint:revive,lll
package mower_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type StartInAreaSrvReq struct {
	msg.Package `ros:"mower_msgs"`
	Area        uint8
}

type StartInAreaSrvRes struct {
	msg.Package `ros:"mower_msgs"`
}

type StartInAreaSrv struct {
	msg.Package `ros:"mower_msgs"`
	StartInAreaSrvReq
	StartInAreaSrvRes
}
