//autogenerated:yes
//nolint:revive,lll
package msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type GPSControlSrvReq struct {
	msg.Package `ros:"msgs"`
	GpsEnabled  uint8
}

type GPSControlSrvRes struct {
	msg.Package `ros:"msgs"`
}

type GPSControlSrv struct {
	msg.Package `ros:"mower_msgs"`
	GPSControlSrvReq
	GPSControlSrvRes
}
