//autogenerated:yes
//nolint:revive,lll
package msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type MowerControlSrvReq struct {
	msg.Package  `ros:"msgs"`
	MowEnabled   uint8
	MowDirection uint8
}

type MowerControlSrvRes struct {
	msg.Package `ros:"msgs"`
}

type MowerControlSrv struct {
	msg.Package `ros:"mower_msgs"`
	MowerControlSrvReq
	MowerControlSrvRes
}
