//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type AppendMapSrvReq struct {
    msg.Package `ros:"mower_map"`
    Bagfile string
}



type AppendMapSrvRes struct {
    msg.Package `ros:"mower_map"`
}

type AppendMapSrv struct {
    msg.Package `ros:"mower_map"`
    AppendMapSrvReq
    AppendMapSrvRes
}
