//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
    "github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)


type MapArea struct {
    msg.Package `ros:"mower_map"`
    Name string
    Area geometry_msgs.Polygon
    Obstacles []geometry_msgs.Polygon
}

