//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type PersistNextGlobalPlanSrvReq struct {
    msg.Package `ros:"mower_map"`
    Persist bool
}



type PersistNextGlobalPlanSrvRes struct {
    msg.Package `ros:"mower_map"`
}

type PersistNextGlobalPlanSrv struct {
    msg.Package `ros:"mower_map"`
    PersistNextGlobalPlanSrvReq
    PersistNextGlobalPlanSrvRes
}
