//autogenerated:yes
//nolint:revive,lll
package mower_map

import "github.com/bluenviron/goroslib/v2/pkg/msg"

type MowerMapReplaceArea struct {
	Area             MapArea
	IsNavigationArea bool `rosname:"isNavigationArea"`
}

type ReplaceMowingAreaSrvReq struct {
	msg.Package `ros:"mower_map"`
	Areas       []MowerMapReplaceArea
}
