//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)

type SetDockingPointSrvReq struct {
	msg.Package `ros:"mower_map"`
	DockingPose geometry_msgs.Pose
}

type SetDockingPointSrvRes struct {
	msg.Package `ros:"mower_map"`
}

type SetDockingPointSrv struct {
	msg.Package `ros:"mower_map"`
	SetDockingPointSrvReq
	SetDockingPointSrvRes
}
