//autogenerated:yes
//nolint:revive,lll
package dynamic_reconfigure

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ConfigDescription struct {
    msg.Package `ros:"dynamic_reconfigure"`
    Groups []Group
    Max Config
    Min Config
    Dflt Config
}

