//autogenerated:yes
//nolint:revive,lll
package dynamic_reconfigure

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type GroupState struct {
    msg.Package `ros:"dynamic_reconfigure"`
    Name string
    State bool
    Id int32
    Parent int32
}

