//autogenerated:yes
//nolint:revive,lll
package xbot_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type ActionResponse struct {
    msg.Package `ros:"xbot_msgs"`
    ActionId string
    RequestId string
    Response string
}

