//autogenerated:yes
//nolint:revive,lll
package xbot_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type RegisterActionsSrvReq struct {
	msg.Package `ros:"xbot_msgs"`
	NodePrefix  string
	Actions     []ActionInfo
}

type RegisterActionsSrvRes struct {
	msg.Package `ros:"xbot_msgs"`
}

type RegisterActionsSrv struct {
	msg.Package `ros:"xbot_msgs"`
	RegisterActionsSrvReq
	RegisterActionsSrvRes
}
