//autogenerated:yes
//nolint:revive,lll
package xbot_msgs

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type RobotState struct {
    msg.Package `ros:"xbot_msgs"`
    BatteryPercentage float32
    Emergency bool
    IsCharging bool
    GpsPercentage float32
    CurrentActionProgress float32
    CurrentState string
    CurrentSubState string
    CurrentArea int16
    CurrentPath int16
    CurrentPathIndex int16
    RobotPose AbsolutePose
}

