//autogenerated:yes
//nolint:revive,lll
package xbot_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"time"
)

type SensorDataString struct {
	msg.Package `ros:"xbot_msgs"`
	Stamp       time.Time
	Data        string
}
